FROM node:24-alpine AS build

ENV CI=true
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@9.15.9 --activate

COPY package.json pnpm-lock.yaml .npmrc ./
COPY patches ./patches
RUN pnpm install --no-frozen-lockfile

COPY . .

ARG VITE_SERVER_URL=
ARG VITE_WS_URL=
ARG VITE_APP_URL=
ARG VITE_RUGIN_CDN=
ARG VITE_DEV_MODE=false
ARG VITE_MOBILE_WIDTH=850
ARG VITE_MESSAGE_LIMIT=50
ARG VITE_TURNSTILE_SITEKEY=
ARG VITE_EMOJI_URL=
ARG VITE_OFFICIAL_SERVER=rugin
ARG VITE_LIVEKIT_ENABLED=false
ARG VITE_GOOGLE_CLIENT_ID=
ARG VITE_GOOGLE_API_KEY=

ENV VITE_SERVER_URL=$VITE_SERVER_URL
ENV VITE_WS_URL=$VITE_WS_URL
ENV VITE_APP_URL=$VITE_APP_URL
ENV VITE_RUGIN_CDN=$VITE_RUGIN_CDN
ENV VITE_DEV_MODE=$VITE_DEV_MODE
ENV VITE_MOBILE_WIDTH=$VITE_MOBILE_WIDTH
ENV VITE_MESSAGE_LIMIT=$VITE_MESSAGE_LIMIT
ENV VITE_TURNSTILE_SITEKEY=$VITE_TURNSTILE_SITEKEY
ENV VITE_EMOJI_URL=$VITE_EMOJI_URL
ENV VITE_OFFICIAL_SERVER=$VITE_OFFICIAL_SERVER
ENV VITE_LIVEKIT_ENABLED=$VITE_LIVEKIT_ENABLED
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_GOOGLE_API_KEY=$VITE_GOOGLE_API_KEY

RUN pnpm build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY docker/40-runtime-config.sh /docker-entrypoint.d/40-runtime-config.sh
RUN sed -i 's/\r$//' /docker-entrypoint.d/40-runtime-config.sh \
  && chmod +x /docker-entrypoint.d/40-runtime-config.sh
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80